import express from "express";
import {
  register,
  login,
  me,
  updateMe,
  changePassword,
  getSessions,
  revokeSession,
  revokeAllSessions,
  logoutCurrent,
} from "../controllers/authController.js";
import {
  createPairingCode,
  cancelPairingCode,
  claimPairingCode,
  getPairingStatus,
  createLoginTicket,
  pollLoginTicket,
  getTicketInfo,
  authorizeLoginTicket,
  rejectLoginTicket,
} from "../controllers/pairingController.js";
import { authRequired } from "../middleware/auth.js";
import { validateRegister, validateLogin } from "../middleware/validate.js";

const router = express.Router();

router.post("/register", validateRegister, register);
router.post("/login", validateLogin, login);
router.get("/me", authRequired, me);
router.put("/me", authRequired, updateMe);
router.post("/change-password", authRequired, changePassword);

// Device Pairing - Workflow 1 (Code & QR generated by logged-in device)
router.post("/pairing/claim", claimPairingCode);
router.post("/pairing/code", authRequired, createPairingCode);
router.get("/pairing/code/status", authRequired, getPairingStatus);
router.delete("/pairing/code", authRequired, cancelPairingCode);

// Device Pairing - Workflow 2 (Quick QR ticket requested by new device)
router.post("/pairing/ticket", createLoginTicket);
router.get("/pairing/ticket/:ticketId", pollLoginTicket);
router.get("/pairing/ticket/info/:identifier", authRequired, getTicketInfo);
router.post("/pairing/ticket/authorize", authRequired, authorizeLoginTicket);
router.post("/pairing/ticket/reject", authRequired, rejectLoginTicket);

// Sessions
router.get("/sessions", authRequired, getSessions);
router.delete("/sessions", authRequired, revokeAllSessions);
router.delete("/sessions/:id", authRequired, revokeSession);
router.post("/logout", authRequired, logoutCurrent);

export default router;
