import express from "express";
import { getCategories, getCategory, getCategoryStats, createCategory, updateCategory, deleteCategory } from "../controllers/categoryController.js";
import { authRequired, authOptional } from "../middleware/auth.js";
import { validateIdParam, validateCategory } from "../middleware/validate.js";
const router = express.Router();
router.get("/stats", authOptional, getCategoryStats);
router.get("/", authOptional, getCategories);
router.get("/:id", authOptional, validateIdParam, getCategory);
router.post("/", authRequired, validateCategory, createCategory);
router.put("/:id", authRequired, validateIdParam, validateCategory, updateCategory);
router.patch("/:id", authRequired, validateIdParam, validateCategory, updateCategory);
router.delete("/:id", authRequired, validateIdParam, deleteCategory);
export default router;
